apiVersion: v1
kind: Secret
metadata:
  name: payment
type: Opaque
data:
 AMQP_USER :  cm9ib3Nob3A=
 AMQP_PASS: cm9ib3Nob3AxMjM=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: roboshop
  labels:
    app: payment
    project: roboshop 
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
      project: roboshop 
      tier: backend
  template:
    metadata:
      labels:
        app: payment
        project: roboshop 
        tier: backend
    spec:
      containers:
      - name: payment
        image: raviraveen1/payment:v2
        imagePullPolicy: Always
        envFrom:
         - secretRef:
              name: payment 


---
apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: roboshop
spec:
  selector:
    app: payment
    project: roboshop 
    tier: backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
