apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    app: rabbitmq
    project: roboshop 
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
      project: roboshop 
      tier: db
  template:
    metadata:
      labels:
        app: rabbitmq
        project: roboshop 
        tier: db
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq
        imagePullPolicy: Always



---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: roboshop
spec:
  selector:
    app: rabbitmq
    project: roboshop 
    tier: db
  ports:
  - protocol: TCP
    port: 5672
    targetPort: 5672


