apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    app: mongodb
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
      tier: db
  template:
    metadata:
      labels:
        app: mongodb
        tier: db
    spec:
      containers:
      - name: mongodb
        image: raviraveen/mongodb:v1 
        imagePullPolicy: Always
        ports:
        - containerPort: 2707
