apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
data:
  MYSQL_DATABASE: "cities"
  MYSQL_USER: "shipping"

---
apiVersion: v1
kind: Secret
metadata:
  name: mysql
type: Opaque
data:
 MYSQL_ROOT_PASSWORD : Um9ib1Nob3BAMQ==
 MYSQL_USER: c2hpcHBpbmcK
 MYSQL_PASSWORD: Um9ib1Nob3BAMQ==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: roboshop
  labels:
    app: mysql
    project: roboshop 
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      project: roboshop 
      tier: db
  template:
    metadata:
      labels:
        app: mysql
        project: roboshop 
        tier: db
    spec:
      containers:
      - name: mysql
        image: raviraveen1/mysql:v2
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
             name: mysql
          - secretRef:
              name: mysql
          




---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: roboshop
spec:
  selector:
    app: mysql
    project: roboshop 
    tier: db
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306


