apiVersion: v1
kind: ConfigMap
metadata:
  name: user
data:
 MONGO: "true"
   
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: roboshop
  labels:
    app: user
    project: roboshop 
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
      project: roboshop 
      tier: backend
  template:
    metadata:
      labels:
        app: user
        project: roboshop 
        tier: backend
    spec:
      containers:
      - name: user
        image: raviraveen1/user:v1 
        imagePullPolicy: Always
        envFrom:
         - configMapRef:
              name: user 


---
apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: roboshop
spec:
  selector:
    app: user
    project: roboshop 
    tier: backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080


